// Каталог рідкісних резервів, перенесений з таблиці «HB резерви».
//
// Два аркуші таблиці — це два ранги, а не два типи речей: Аркуш1 — ранг 1,
// Аркуш2 — ранг 2. Ціни з таблиці свідомо НЕ перенесені: вони застарілі, і ці
// резерви не купуються. Вони потрапляють до пілота як частина нагороди за місію
// й лежать на складі (до VAULT_CAP), доки їх не візьмуть на місію, де вони згорять.
//
// key збирається з рангу та ID рядка, а не з назви: у таблиці є дублі назв
// (ранг 1, ID 6 і 9 — обидва CONCUSSIVE BRACER) і один порожній рядок назви
// (ранг 1, ID 8), тож назва ключем бути не може.
//
// Тексти лишені мовою оригіналу таблиці.

import { RESERVES } from './reserves';

export const RARE_RANKS = [1, 2];

// Скільки рідкісних резервів вміщує склад пілота. Покращення ангару «Місце на складі»,
// що його розширювало, прибрано з ангару — склад завжди базовий.
export const VAULT_CAP_BASE = 5;

export function vaultCap() {
  return VAULT_CAP_BASE;
}

export const RARE_RESERVES = [
  { key: 'r1-01', rank: 1, name: 'SNAP HOOKS', action: 'Quick Action', tags: 'Limited 1', desc: 'Automatically grapple an adjacent target.', flavor: 'Cabled hooks launched from exterior-mounted ejection points for rapid, intimate engagement.' },
  { key: 'r1-02', rank: 1, name: 'MOLECULAR WHETSTONE', action: 'Free Action', tags: '1/round, Limited 1', desc: 'After you successfully hit with a melee attack, but before damage is rolled, spend this reserve as a free action to cause the target to become Shredded until the end of the current turn.', flavor: "A device installed in a weapon's grip that sends an autophagic pulse up the blade, sharpening it before impact." },
  { key: 'r1-03', rank: 1, name: 'KINETIC PULSE COIL', action: 'Quick Action', tags: 'Limited 1', desc: 'Ram every character in Burst 1.', flavor: 'Chassis-mounted woofers. Kinetic-absorbant coils gather latent energy from normal actions, such as walking, running, or fighting, until released with explosive force.' },
  { key: 'r1-04', rank: 1, name: '"ICARUS" MULTISTAGE BOOSTER', action: 'Free Action', tags: 'Limited 1', desc: 'When you make a standard move, spend this reserve as a free action to move your speed in a straight line.', flavor: 'Dual break-away boosters that help close the distance; or increase it, as needed.' },
  { key: 'r1-05', rank: 1, name: 'REDUNDANT CLADDING', action: 'Reaction', tags: 'Limited 1', desc: "Trigger: You're successfully hit by an attack. Effect: You gain resistance to that attack, but are impaired until the end of your next turn.", flavor: "Rough, but effective, armor plating that can take hits your normal armor might find disagreeable. Won't protect you from cockpit whiplash as a result of said impacts." },
  { key: 'r1-06', rank: 1, name: 'CONCUSSIVE BRACER', action: 'Free Action', tags: 'Limited 2', desc: 'When you successfully hit with a Ram, spend this reserve as a free action to give the target Impaired until the end of their next turn.', flavor: 'An external-fit gauntlet of extraordinary weight. The stored concussive energy is expended almost as quickly as its victims fall to the ground.' },
  { key: 'r1-07', rank: 1, name: '"CUIRASS" SHIELD GENERATOR', action: 'Quick Action', tags: '1/round, Deployable, Shield, Limited 2', desc: '1/round, Deploy a Cuirass Shield Generator in a free adjacent space. Creates a Burst 1 energy field upon deployment. The next 3 attacks that target any character or object within this shield treat each target as having hard cover. (Cuirass Shield Generator: Size: 1, HP 10, Evasion: 5)', flavor: 'An emitter dish mounted on a rudimentary tripod. Its power supply is limited, but consistent enough to see frequent use in the field as a quick means of fortifying positions.' },
  { key: 'r1-08', rank: 1, name: 'БЕЗ НАЗВИ (ID 8)', action: 'Quick Action', tags: 'Limited 1', desc: 'Reload any Loading weapon.', flavor: 'Bullet go in, bullet go out.' },
  { key: 'r1-09', rank: 1, name: 'CONCUSSIVE BRACER (ID 9)', action: 'Quick Action', tags: 'Limited 1', desc: 'You or an allied character within Range 3 immediately clears all Burn.', flavor: 'Sometimes a high tech problem needs a low tech solution.' },
  { key: 'r1-10', rank: 1, name: 'ADAPTIVE ROUNDS', action: 'Protocol', tags: 'Limited 5', desc: 'Change the damage type of your next ranged attack to either Kinetic, Energy, or Explosive.', flavor: 'Each shell casing is helpfully color coded to prevent accidental incineration in volatile environments.' },
  { key: 'r1-11', rank: 1, name: 'OVERPOWERED COILS', action: 'Reaction', tags: 'Limited 1', desc: 'Trigger: Your attack deals bonus damage of any kind. Effect: The target is knocked back spaces equal to the bonus damage dealt.', flavor: 'A cartridge mounted in convenient thumb reach for quick activation, bolstering the efficacy of existing weapon modifications. Burns out quick, so pick your moment.' },
  { key: 'r1-12', rank: 1, name: 'REACTIVE SHUNT', action: 'Free Action', tags: 'Limited 1', desc: 'When you brace, automatically clear all heat as a free action. All characters adjacent to you take heat equal to half of what you cleared.', flavor: "An emergency vent built to disseminate excess reactor waste as quickly as possible. Make your choices everyone else's problem." },
  { key: 'r1-13', rank: 1, name: '"THUMB" CANNON', action: 'Protocol', tags: 'Limited 2', desc: 'You may Ram from up to range 5 until the end of this turn.', flavor: 'Arm-mounted, bulky, and thunderous, pilots are recommended to wear ear plugs before they charge it up.' },
  { key: 'r1-14', rank: 1, name: 'FUEL RESERVES', action: 'Protocol', tags: 'Limited 2', desc: 'All movement actions (standard move, Boost, etc.) you take this round may move 1 additional space.', flavor: 'Keep a little extra in the tank.' },
  { key: 'r1-15', rank: 1, name: 'ACHILLES ROUND', action: 'Passive', tags: 'Limited 3', desc: "When you reload any weapon, that weapon's next attack gains the Overkill tag.", flavor: 'Someone carved a skull and crossbones into the shell casing.' },
  { key: 'r1-16', rank: 1, name: 'DEMO CHARGE', action: 'Quick Action', tags: 'Limited 1', desc: 'Immediately deal 40 Kinetic damage to an adjacent object or piece of terrain.', flavor: 'Clear the view.' },
  { key: 'r1-17', rank: 1, name: 'EXPENDABLE RIFLING', action: 'Protocol', tags: 'Limited 3', desc: 'Your next ranged attack has its Range extended by 5.', flavor: 'A long barrel that screws to the end of your gun. Designed to fit all standard GMS munitions.' },
  { key: 'r1-18', rank: 1, name: 'MASS-ECHO CHARGE', action: 'Passive', tags: 'Limited 1', desc: 'Whenever you successfully hit with a tech attack, roll 1D20. On a natural 20, the target is stunned after the attack resolves. This reserve persists until triggered.', flavor: "A small, silvery chip installed in your mech's computer core. Contains enough malicious paracode to shut down a city block, so it can only be used in short bursts." },
  { key: 'r1-19', rank: 1, name: 'SUPERMUNITIONS', action: 'Protocol', tags: 'Limited 1', desc: "Your next ranged attack that isn't a Cone, Line, or Burst gains Blast 1, in addition to its normal profile. If it's already Blast 1, it becomes Blast 2, and so on.", flavor: 'Volatile, modular charges that multiply the tactical and geographic scope of all standard munitions.' },
  { key: 'r1-20', rank: 1, name: 'SILHOUETTE SCRAMBLERS', action: 'Protocol', tags: 'Limited 3', desc: 'Attacks originating from further than Range 3 treat you as having hard cover until the end of your next turn.', flavor: "A cyber warfare suite that scatters and distorts your image on all visual wavelengths. You'll be less of a target and more of a cubist suggestion." },
  { key: 'r1-21', rank: 1, name: 'AUTO-FLECHETTES', action: 'Reaction', tags: 'Limited 1', desc: 'Trigger: You successfully hit an Immobilized character with an attack. Effect: Deal 1D6 bonus damage.', flavor: 'Shoulder-mounted launchers that fire screaming bands of iron at speeds too slow to rely on in the heat of combat, but the trapped prey can do nothing but watch.' },
  { key: 'r1-22', rank: 1, name: 'ICE OUT DEMO DISC', action: 'Quick Action', tags: 'Limited 2', desc: 'Spend this reserve to gain Immunity to all tech actions until the start of your next turn.', flavor: 'Comes free in the mail with a subscription to any one of a number of exciting Smith Shimano services.' },
  { key: 'r1-23', rank: 1, name: 'SPIDER TRAP', action: 'Quick Action', tags: 'Deployable, Limited 3', desc: 'Deploy an electrified mesh that encompasses a free Blast 1 area within Range 5. Characters who start their turn in the Spider Trap or who enter it for the first time in a round must make an Engineering save or become Immobilized.', flavor: "Your parlor is the effective combat theater of the current engagement and the fly is a six ton somersaulting war robot with a nuclear reactor, but the principle isn't too far off." },
  { key: 'r1-24', rank: 1, name: 'SERVO LIMITER BYPASS', action: 'Free Action', tags: '1/round, Limited 3', desc: '1/round, When you successfully hit with a melee attack, spend this reserve as a free action to deal 3 Knockback, in addition to any other knockback effects. After the attack is resolved, roll 1D6; on a 5+, your mech is Impaired until the end of your next turn.', flavor: 'This handy plug-n-play override lets you get around the factory-standard failsafes native to the original printing.' },
  { key: 'r1-25', rank: 1, name: 'FREQUENCY ALIGNMENT NODE', action: 'Quick Action', tags: 'Limited 2', desc: 'Clear the Jammed condition and gain immunity to Jammed until the end of your next turn.', flavor: 'Ancillary nodes connected to your sensor array that broadcast constantly shifting, synchronistic frequencies. Trick hostile jamming technology into following a ghost of your mech down a dark alley.' },
  { key: 'r1-26', rank: 1, name: 'EMERGENCY HEAT TRAP', action: 'Reaction, Quick Action', tags: 'Limited 1', desc: 'The next time you would gain Heat from a hostile source, spend this reserve as a reaction to reduce the amount to 0 and gain a Shunt Charge. The Firecracker Charge lasts until used, but expires at the end of the scene. As a quick action on any of your turns, you may lob the Firecracker Charge at a hostile enemy character within Range 5. They must pass an Agility save or take energy damage equal to the Heat that you would have gained by the triggering effect.', flavor: "Yeah, pretty handy. They say some merc invented these in his garage with a box of spare parts 'cause his team kept melting their reactors." },
  { key: 'r1-27', rank: 1, name: 'KNOCKOUT CHARGE', action: 'Reaction', tags: 'Limited 3', desc: 'Trigger: Critically Hit with a ranged or melee weapon. Effect: The target of your attack is knocked Prone and becomes Slowed until the end of their next turn.', flavor: 'An impact-sensitive charge applied to blade, hammerhead, or bullet. Anyone hit with this is gonna need a minute.' },
  { key: 'r1-28', rank: 1, name: 'ACTIVE CAMO', action: 'Quick Action', tags: 'Limited 1', desc: 'Become Invisible until the start of your next turn.', flavor: "An emitter device installed right about where your mech's sternum would be. The energy pattern it projects bends the light around you, but the odd, blurry defect can clue the perceptive marksman as to where you might be skulking." },
  { key: 'r1-29', rank: 1, name: 'HOLO DECOY', action: 'Quick Action', tags: '1/round, Limited 3', desc: '1/round, Create a holographic decoy of yourself. This decoy moves your Speed in a straight line from your current position; it is unaffected by difficult terrain but is stopped by obstructions and characters in its path. Hostile characters who start their turn within line of sight and range of the hologram must first make a System save or be forced to attack the decoy. The decoy shares your size, can benefit from cover, and has Evasion 10, E-Defense 10, and 1 HP. It disappears if it takes heat or damage, or at the end of your next turn. If you create a second decoy, the previous one disappears.', flavor: 'The decoy can be programmed to execute any number of gestures from a vast library of "emotes." Sure to infuriate any and all hostiles from Core to Shore.' },
  { key: 'r1-30', rank: 1, name: 'PUNISHER SYLO', action: 'Free Action', tags: '1/round, Limited 3', desc: '1/round When you critically hit with any attack, deal 3 Explosive damage to a different target within Range 15 as a free action.', flavor: 'A quick-launch tube armed with three fire-and-forget rockets.' },
  { key: 'r1-31', rank: 1, name: 'BODY FLICKER DRIVE', action: 'Protocol', tags: 'Limited 3', desc: 'Teleport whenever you Boost until the end of the current turn.', flavor: 'An experimental drive plugged right into your reactor. Painfully cold to the touch, so make sure to wear the special protective gloves it came with during installation.' },
  { key: 'r1-32', rank: 1, name: 'PREDATOR/PREY PING', action: 'Quick Action', tags: 'Limited 2', desc: 'Remove Hidden and Invisible from one hostile character in Sensors and line of sight. That character cannot regain either Hidden or Invisible until the end of their next turn.', flavor: 'A chunky power modulator that interfaces directly with your sensor array. Enhances the effective precision of your sensors in quick, powerful bursts, but continuous use will blow them out like a bad fuse.' },
  { key: 'r1-33', rank: 1, name: 'JAEGER SHOCKS', action: 'Free Action', tags: '1/round, Limited 2', desc: "1/round, If your standard move or Boost ends next to hard cover equal to or greater than your mech's Size, spend this reserve to immediately move 2 spaces in any direction.", flavor: 'Kinetic-absorbant shocks installed in the ankle, knee, and hip joints of your mech. Allows even a multi-ton machine to quickly navigate through tight urban corridors without fear of toppling the whole block.' },
  { key: 'r1-34', rank: 1, name: 'SHINE-CLASS ENERGY SHIELD', action: 'Free Action', tags: 'Limited 1', desc: "When you're successfully hit by a ranged or melee attack, spend this reserve to gain Overshield equal to your Grit+3 before damage is rolled. These Overshield disappears after the attack is resolved.", flavor: 'An energy shield that quickly snaps into place at the instant of violent impact. Popularized by a merc pilot by the name of McCloud, infamous for his quick reflexes and fancy footwork.' },
  { key: 'r1-35', rank: 1, name: 'LIVING PARTICULATE NEXUS', action: 'Quick Action', tags: '1/round, Limited 1', desc: '1/round, Spend this reserve as a quick action to release a Burst 1 cloud of nanites that lasts until the start of your next turn. Hostile characters who end their turn in this cloud, or who enter it for the first time in a round, take 2AP kinetic damage.', flavor: "Mmmm... no, I'm pretty sure it's just gray-wash." },
  { key: 'r1-36', rank: 1, name: '"CASTLE" TECH SUITE', action: 'Quick Action', tags: 'Limited 1', desc: 'Spend this reserve as a quick action. Gain a +3 bonus to System saves, a +3 bonus to your e-defense, and a +3 bonus to tech attacks. This effect lasts until the end of your next turn.', flavor: "An advanced firewall program that drastically increases your computer's combat efficacy." },
  { key: 'r1-37', rank: 1, name: 'SAAS-CQB-TDDS', action: 'Free Action', tags: 'Limited 1', desc: 'After you hit with Overwatch, spend this reserve to immediately Overwatch against a different character in range with the same weapon. You cannot attack the same character twice.', flavor: 'A modification to your sensors that populates your HUD with predictive-analysis targets before you even see them.' },
  { key: 'r1-38', rank: 1, name: 'ANAGUMA-CLASS SUBALTERN', action: 'Quick Action', tags: 'Drone, Limited 1', desc: "Spend this reserve to deploy a Anaguma combat subaltern within Sensors and line of sight. Whenever you successfully attack, the Anaguma deals 3 Energy damage to the same target as long as it's within Range 5 of the target when the attack hits. When the Anaguma is destroyed, it detonates in a Burst 2 explosion. Characters caught in the explosion must make an Agility save or take 1D6+2 Explosive damage. They take half of that on success. The Anaguma cannot be recalled, but it can be moved with talents and abilities. It expires at the end of the scene. (Anaguma-Class Subaltern: Size: 1/2, HP 10, Evasion: 5)", flavor: "It's programmed with a friendly, cheerful persona package that nevertheless comes off as disturbingly enthusiastic about its own imminent self-destruction." },
  { key: 'r1-39', rank: 1, name: 'AIM COMPENSATOR', action: 'Reaction', tags: 'Limited 1', desc: 'Trigger: You miss with any ranged or melee attack. Effect: Deal 2 Reliable damage.', flavor: "A hydraulic brace installed at your mech's shoulder and elbow that corrects your aim in the heat of combat." },
  { key: 'r1-40', rank: 1, name: 'TROJAN REBOUND', action: 'Reaction', tags: 'Limited 2', desc: 'Trigger: A hostile character within Range 10 is Slowed. Effect: That character is now Immobilized for the same duration as the triggering effect.', flavor: "A hungry, aggressive paracode that tugs on the leash it's been given." },
  { key: 'r1-41', rank: 1, name: 'SUBSPACE FIRING CHAMBER', action: 'Free Action', tags: '1/round, Limited 3', desc: '1/round, spend this reserve as a free action during any character’s turn to deal 1 damage to any character on the map regardless of range or line of sight. This damage cannot be reduced in any way.', flavor: 'It looks like a typical sidearm, except it has no muzzle; only a sheer, flat surface where bullets ought to exit. Looking at the gun too long after firing it might give some pilots motion sickness.' },
  { key: 'r1-42', rank: 1, name: 'SONIC EMITTER', action: 'Quick Action', tags: 'Limited 1', desc: 'Spend this reserve as a quick action to detonate a Size 1 object or piece of hard cover within Range 10 and line of sight. Characters within Burst 1 of the detonation must make an Agility save or take 1D6 explosive damage and 2 Burn. On success, they take no explosive damage and 1 Burn.', flavor: 'A dish made out of a series of concentric, hollow rings. Tension can be adjusted for concentrated frequencies.' },
  { key: 'r1-43', rank: 1, name: 'DETRITUS LAUNCHER', action: 'Quick Action', tags: 'Limited 1', desc: 'Launch a cloud of obstructive micro-debris in Cone 7. This zone counts as difficult terrain and soft cover until the end of the current round. Characters who start their turn in this cloud or enter it for the first time in the round become Impaired.', flavor: 'A rattling, makeshift hunk of iron with a design philosophy closer to Queen Victoria than John Creighton Harrison.' },
  { key: 'r1-44', rank: 1, name: 'THERMAL TRANSFER CHAMBER', action: 'Quick Action', tags: 'Limited 2', desc: '1/round, spend this reserve as a quick action to add bonus energy damage equal to your current Burn to your next successful attack.', flavor: 'A weapon mod that looks a bit like an old water radiator. It gathers energy from ambient local temperature.' },
  { key: 'r1-45', rank: 1, name: 'EMERGENCY BACKUP MINE', action: 'Free Action', tags: 'Limited 2', desc: "Spend this reserve whenever you place a mine to place a second mine as a free action. This second mine does not count against that system's Limited item count.", flavor: 'A couple of spare mines you found at the bottom of a crate.' },
  { key: 'r1-46', rank: 1, name: 'WIDE AREA IMPACT DISTRIBUTOR', action: 'Reaction', tags: 'Limited 1', desc: 'Trigger: You take any damage from a ranged or melee attack. Effect: The damage of that attack is immediately reduced to 1 and is applied to you and all characters within Range 5. This single point of damage cannot be reduced in any way.', flavor: "A peculiar energy shield that relies on expanded surface area to lessen the impact of hostile munitions. One mech's surface alone is rarely enough, so it uses instantaneous substatic pings to borrow the rest." },
  { key: 'r1-47', rank: 1, name: 'MAG LASSO', action: 'Reaction', tags: 'Limited 2', desc: 'Trigger: An allied character within Range 5 takes Kinetic or Explosive damage. Effect: You may deal half of that damage to a hostile character within Range 5.', flavor: "A hollow, high-tech node installed somewhere in your mech's hand. Many pilots prefer the palm for dramatic effect, but anywhere will do. Catches bullets and missiles as easy as dandelions." },
  { key: 'r1-48', rank: 1, name: 'REACTOR BLUFF', action: 'Quick Action', tags: 'Limited 2', desc: 'Spend this reserve as a quick action to immediately enter the Danger Zone with no heat gain. This lasts until the end of the current turn. You may still gain heat through other means normally.', flavor: "Reactors aren't smart. They don't think, they don't reason, they don't solve problems. But they can be tricked." },
  { key: 'r1-49', rank: 1, name: 'VOLATILE ENERGY CELL', action: 'Free Action', tags: 'Limited 2', desc: 'When you deal any Energy damage, spend this reserve to deal 2 Burn as bonus damage.', flavor: "There's a little tab you can rip off at the end of the cell. Yeah, right there, that's the-Woah, woah, woah! Don't do it NOW you idiot!!!" },
  { key: 'r1-50', rank: 1, name: 'KINGS_FOLLOWUP.EXE', action: 'Full Action', tags: 'Limited 2', desc: 'Spend this reserve to target a hostile unit in line of sight and sensors that has any Burn. That character immediately takes damage as if they had failed the end of turn Engineering check to clear Burn.', flavor: "A sinister invasion package that interferes with a mech's fire suppression features." },

  { key: 'r2-01', rank: 2, name: 'SLINGSHOT PORTAL', action: 'Quick Action', tags: '1/scene', desc: "Place a marker on your current space, then immediately teleport to any free space within Range 20 and line of sight. You automatically teleport back to that marker at the end of your next turn unless you're Stunned or Immobilized.", flavor: 'The Slingshot Portal was originally designed for clandestine scouting maneuvers, but field captains quickly discovered its offensive potential.' },
  { key: 'r2-02', rank: 2, name: 'PURVIEW-GRADE DUCT TAPE', action: 'Free Action', tags: '1/mission or operation', desc: 'Repair a destroyed weapon or system without spending your Repair Cap.', flavor: "Sometimes the best solutions in life are cheap. Unfortunately, Harrison Armory doesn't make anything cheap." },
  { key: 'r2-03', rank: 2, name: 'COOLANT RIG', action: 'Passive', tags: '', desc: 'Each time you gain heat from a hostile source, the total amount of heat is reduced by 1.', flavor: 'A complex network of pipes, tubes, and pads strategically set up around your reactor to ensure that you can push it a little harder than usual.' },
  { key: 'r2-04', rank: 2, name: 'INSIGHT-CLASS COMP/CON', action: 'Free Action', tags: '1/scene', desc: '1/scene, perform one quick action as a free action. It cannot be an attack and it cannot force a save.', flavor: 'The Insight-Class is designed to help you maintain a tactical advantage while you focus on more aggressive maneuvers.' },
  { key: 'r2-05', rank: 2, name: 'RADIANT TARGET ACTUATOR', action: 'Passive', tags: '1/round', desc: "1/round, If you don't move before firing a Launcher, you get +1 Accuracy.", flavor: "A software update that improves each missile's ability to maintain target priority. They just need a second or two to make a lock." },
  { key: 'r2-06', rank: 2, name: 'COUNTERWEIGHT POMMEL', action: 'Passive', tags: '', desc: "If your melee weapons don't have the Reliable tag, they gain Reliable 1. If they already have the Reliable tag, its value increases by 1.", flavor: 'A pommel printed to the exact weight and specifications of your weapon allowing for field-optimal balance.' },
  { key: 'r2-07', rank: 2, name: 'PISTON BRACE', action: 'Reaction', tags: '1/round', desc: 'Trigger: An enemy knocks you back. Effect: You may ignore that movement.', flavor: "Emergency-launch pistons installed in the calves or feet of your mech. Whenever you find yourself stumbling, they'll be there to catch your fall." },
  { key: 'r2-08', rank: 2, name: 'FORCED REBOOT PACKAGE', action: 'Quick Action', tags: '1/scene', desc: '1/scene, you may clear the Stunned condition for you or an adjacent allied character as a quick action. This can be used even while Stunned. You or your ally then become Impaired and Slowed until the end of their next turn.', flavor: "Being stunned is considered by many pilots to be a worst-case scenario, but it's nothing a little software can't fix." },
  { key: 'r2-09', rank: 2, name: 'CHIP SHIELDS', action: 'Passive', tags: '1/round', desc: '1/round, If you would only take 1 damage from a ranged or melee attack, reduce it to 0 damage.', flavor: "An overshield with an extremely low energy draw. It isn't strong enough to ward off direct attacks, but it's sufficient enough to let you ignore ambient wear and tear." },
  { key: 'r2-10', rank: 2, name: 'TREMOR CHARGE', action: 'Passive', tags: '1/scene', desc: "1/scene, any knockback effect you inflict on a hostile character also knocks them prone, if it doesn't already.", flavor: "An explosive charge that detonates upon impact with the target. While it doesn't do any physical damage, it will knock them off their feet." },
  { key: 'r2-11', rank: 2, name: 'EMERGENCY FOAM DISPENCER', action: 'Passive', tags: '1/scene', desc: '1/scene, automatically clear any burn you have at the end of your turn.', flavor: "For untold thousands of years, fire has remained one of mankind's cruelest and most effective weapons. You'd be a fool not to expect it." },
  { key: 'r2-12', rank: 2, name: 'PLIABLE EXPLOSIVE CASING', action: 'Passive', tags: '', desc: 'All grenades can be thrown an additional 1 space.', flavor: 'Gives your grenades a little extra bounce.' },
  { key: 'r2-13', rank: 2, name: 'GHILLIE MANTLE', action: 'Reaction', tags: '1/scene', desc: "Trigger: You're targeted by a ranged attack while benefiting from hard cover. Effect: You count as Invisible until the attack resolves.", flavor: "Most combat theorists will tell you that mundane camouflage is useless in this era of high tech weaponry, but experienced mercenaries know that there's a big difference between theory and praxis." },
  { key: 'r2-14', rank: 2, name: 'USHTABI ROUND', action: 'Protocol', tags: '1/scene', desc: '1/scene, the next successful attack you make with a ranged weapon deals the average of its total damage based on the number of dice rolled, as follows: 1d3 (2), 1d6 (4), 2d6 (7), 3d6 (11), 4d6 (14).', flavor: 'Try not to look at this bullet too hard.' },
  { key: 'r2-15', rank: 2, name: 'EXTENDED BARREL', action: 'Passive', tags: '', desc: 'All Rifle weapons have their maximum Range increased by 1.', flavor: 'Every meter counts.' },
  { key: 'r2-16', rank: 2, name: 'DEVASTATOR SHELLS', action: 'Passive', tags: '', desc: 'All Cannon weapons ignore soft cover.', flavor: 'At a certain point, the amount of damage a gun can dole out will nullify any opposing terrain advantage.' },
  { key: 'r2-17', rank: 2, name: 'BREACHER DOCTRINE', action: 'Free Action', tags: '1/round', desc: '1/round, before skirmishing with a CQB weapon, you may move 1 space. This movement ignores engagement and does not provoke reactions.', flavor: 'A software package that allows your mech finer motor control in high-collision environments.' },
  { key: 'r2-18', rank: 2, name: 'HEAVY SHIELD', action: 'Passive', tags: '', desc: 'Adjacent allied characters can use you for hard cover.', flavor: 'Installs on forearm-mounted hardpoints, leaving your off-hand free for more offensive tasks.' },
  { key: 'r2-19', rank: 2, name: 'VOLATILE CATALYST', action: 'Passive', tags: '1/round', desc: '1/round, whenever you deal energy damage to a hostile character, deal 1 Energy damage to one other hostile character adjacent to the target.', flavor: "A moderately sized deck charger that allows you to overclock your weapon's energy cells." },
  { key: 'r2-20', rank: 2, name: 'ADVANCED PRINTING MATERIALS', action: 'Passive', tags: '', desc: 'All of your drones and deployables have +1 Armor.', flavor: 'Figure that the cost of drone repair ends up being more in the long run than the cost of a little extra armor.' },
  { key: 'r2-21', rank: 2, name: 'SCATTER MALWARE', action: 'Reaction', tags: '1/round', desc: "Trigger: You trigger an enemy's Overwatch. Effect: You count as having soft cover until the attack is resolved.", flavor: "A reactive invasion package that distorts your profile on the enemy's HUD just enough to make you annoying to hit." },
  { key: 'r2-22', rank: 2, name: 'DONKEY BRACE', action: 'Free Action', tags: '1/scene', desc: '1/scene, you may ignore the Ordnance tag for one attack.', flavor: 'A back-mounted brace that allows you to bring heavier munitions to bear without sacrificing mobility. As robust as this brace is, however, it can only be used a limited number of times before snapping clean in half.' },
  { key: 'r2-23', rank: 2, name: 'EFFICIENT ENERGY EMMITERS', action: 'Passive', tags: '1/round', desc: '1/round, When you gain any Overshields, gain 1 extra point of Overshields.', flavor: "You'd be amazed how much energy goes to waste in most contemporary shielding systems." },
  { key: 'r2-24', rank: 2, name: 'FIELD PATCH', action: 'Protocol', tags: '1/scene', desc: '1/scene, remove the Shredded condition as a protocol, but become Slowed until the end of your next turn.', flavor: 'A quick-seal adhesive slab of metal that slaps over any damage your outer chassis may receive. A bit cumbersome to use in the heat of battle, however.' },
  { key: 'r2-25', rank: 2, name: 'BULL EXO-FRAME', action: 'Passive', tags: '', desc: 'Moving adjacent to characters the same size as you does not stop your movement. Larger characters can still stop you as normal, however.', flavor: "A bulky mantle that fits over your mech's shoulders, allowing you to quite literally charge past whatever hostile may stand in your way." },
  { key: 'r2-26', rank: 2, name: 'XC HARDPOINTS', action: 'Reaction', tags: '1/scene', desc: "Trigger: You're successfully hit by a weapon with the Armor-Piercing tag. Effect: You may ignore that tag for this attack only, allowing your Armor to reduce the damage dealt as normal.", flavor: 'Strategically placed support hardpoints that increase the effective longevity of your chassis armor.' },
  { key: 'r2-27', rank: 2, name: 'TACTICAL SENSOR SUITE', action: 'Passive', tags: '', desc: 'Your sensors get +5 Range when you use the Lock On or Scan quick tech actions.', flavor: 'A software update that boosts your short-range sensors, but only if you keep your finger off the trigger for once in your life.' },
  { key: 'r2-28', rank: 2, name: 'LOCKJAW VIRUS', action: 'Passive', tags: '1/round', desc: '1/round, whenever you successfully hit a hostile character with a tech attack, that character gets +1 Difficulty to the next ranged, melee, or tech attack they make against you.', flavor: "It's just good strategy to prioritize enemy hackers on the field of battle. But what do you do if you are the enemy hacker?" },
  { key: 'r2-29', rank: 2, name: 'ADAPTABLE FIREWALL', action: 'Reaction', tags: '1/scene', desc: "Trigger: You're successfully hit by a hostile tech attack. Effect: You count as Invisible for the next tech attack that targets you.", flavor: 'A defense package that rapidly reprograms itself to keep up with enemy cyber-doctrine.' },
  { key: 'r2-30', rank: 2, name: '"BLACK EYE" FUEL CANISTER', action: 'Protocol', tags: '1/round', desc: '1/round, the first attack you make that deals any amount of Burn damage gains the Reliable 2 tag. This reliable damage is applied as Burn.', flavor: "Don't look directly at the flames. They've been known to cause the careless eye to bleed." },
  { key: 'r2-31', rank: 2, name: 'DEFENSIVE EMP', action: 'Passive', tags: '', desc: 'When you Brace, all adjacent characters are Jammed until the end of their next turn.', flavor: "A core-mounted emitter that releases an electro-magnetic pulse strong enough to scramble anyone breathing down your neck. Just don't use it around your friends, or they'll give you an earful... as soon as their comms are back up, anyway." },
  { key: 'r2-32', rank: 2, name: 'TATTLETALE SCOPE', action: 'Passive', tags: '1/round', desc: "1/round, when you hit with a ranged or tech attack, you learn the target's HP and Heat.", flavor: 'Most pilots can estimate how much damage an enemy can take with a bit of napkin math, but why guess?' },
  { key: 'r2-33', rank: 2, name: 'RESPONSIVE MOBILITY PACKAGE', action: 'Quick Action', tags: '1/scene', desc: '1/scene, when you Boost while adjacent to an allied character, that character may also Boost their speed in any direction.', flavor: 'A software package that links your maneuvering systems with a friendly computer, allowing for synchronized assaults.' },
  { key: 'r2-34', rank: 2, name: 'CHRONOMETRIC SCRAMBLER', action: 'Reaction', tags: '1/scene', desc: 'Trigger: Any hostile character successfully attacks, passes a save or check, or otherwise successfully rolls a die (including NPC feature recharging). Effect: The attack misses, the save or check is failed, or the dice successfully rolled is now a failure, etc. You immediately take 3 heat and become Impaired until the end of your next turn.', flavor: '"Whew, that was a close one." "What was?"' },
  { key: 'r2-35', rank: 2, name: 'LOCUST PROJECTOR', action: 'Quick Action', tags: '1/round, Drone', desc: 'Deploy the Locust Projector within sensors and line of sight as a quick action. Once deployed, the Locust Projector emits a Burst 1 field. All characters in this field gain soft cover and have Immunity to all damage and effects from missed attacks. (Locust Projector: Size: 1/2, HP 5, Evasion 10, EDef 10)', flavor: "A crab-like drone about the size of a dumpster. It's equipped with a suite of point-defense armaments that can intercept anything short of a direct hit." },
  { key: 'r2-36', rank: 2, name: 'REBOUND FIREWALL', action: 'Passive', tags: '1/scene', desc: '1/scene, if you gain the Jammed condition from a hostile character, that character is immediately Jammed, as well.', flavor: "Oh yeah? Screw you, too, buddy! ... I said-uhhh, I said, 'screw you, too.' Do you copy? ... Hello?" },
  { key: 'r2-37', rank: 2, name: 'FIELD PATTERN IDENTIFIER', action: 'Free Action', tags: '1/round', desc: '1/round, Whenever you push or pull a hostile character, you may move 1 space. This movement ignores engagement and does not provoke reactions.', flavor: 'An upgrade to your sensors that allows you to analyze the rapidly evolving variables of any battlefield, plotting the best possible maneuvers to capitalize on an already good situation.' },
  { key: 'r2-38', rank: 2, name: 'SELF-DETONATING DEBRIS CANNISTER', action: 'Quick Action', tags: '1/scene', desc: '1/scene, create a Blast 1 zone of difficult terrain in a free adjacent space as a quick action. This zone lasts for the rest of the scene.', flavor: "A canister full of shrapnel, razor-wire, caltrops, and other similarly hazardous traps. No-man's land on demand." },
  { key: 'r2-39', rank: 2, name: 'CO-PILOT ASSISTANCE SUITE', action: 'Passive', tags: '', desc: 'Your Overwatch attacks can never suffer from Difficulty.', flavor: "A targeting suite developed from IPS-N's WATCHDOG program, but with a greatly reduced cerebral load." },
  { key: 'r2-40', rank: 2, name: 'FIRE SUPPORT APPENDAGES', action: 'Free Action', tags: '1/scene', desc: '1/scene, when you Critically Hit with any ranged or melee attack, you may reload one Loading weapon as a free action.', flavor: "A pair of externally mounted arms that handle the more mundane tasks you don't have the time to bother with." },
  { key: 'r2-41', rank: 2, name: 'REDLINE THRUSTERS', action: 'Free Action', tags: '1/scene', desc: '1/scene, you may Boost as a free action. You cannot Boost again on this turn except through Overcharge.', flavor: 'A pair of back-mounted thrusters that allow you to push your mech beyond factory-recommended speeds.' },
  { key: 'r2-42', rank: 2, name: 'FULL SERVICE EXO-DRONES', action: 'Passive', tags: '', desc: "Your Stabilize full action now clears one additional condition that wasn't caused by one of your own systems, talents, etc. This can be applied to either yourself or an adjacent allied character.", flavor: 'A pair of small, spider-like drones that excel in quick repairs in the heat of combat.' },
  { key: 'r2-43', rank: 2, name: '"BLOODWATER" CHAFF LAUNCHER', action: 'Passive', tags: '1/round', desc: '1/round, whenever you inflict Impaired on a hostile character, they must also pass a Hull save or become Slowed.', flavor: 'A shoulder-mounted launcher that automatically fires a volley of exploding chaff at weakened hostiles. Does negligible damage, but keeps the target effectively neutered.' },
  { key: 'r2-44', rank: 2, name: 'POWER FIST', action: 'Passive', tags: '', desc: 'The first Grapple or Ram you make in a round has +1 Accuracy.', flavor: "A large, oversized gauntlet that fits over one of your mech's hands. Grants the wearer uncontested dominance in close-quarters sparring." },
  { key: 'r2-45', rank: 2, name: 'CLUTTER PACKAGE', action: 'Passive', tags: '', desc: 'Your Invade quick tech action deals 1 additional heat.', flavor: 'Quadruples the size of your basic cyber invasion package with useless data, forcing the enemy computer to draw an equivalent amount of power just to keep all of it out.' },
  { key: 'r2-46', rank: 2, name: 'BLINDSIGHT TARGETING LASER', action: 'Passive', tags: '1/round', desc: '1/round, When you Lock On to a hostile character, they must pass a Systems save or become unable to make voluntarily movements that bring them closer to you until the end of their next turn. Cannot be used on the same character more than 1/scene.', flavor: "A head-mounted laser that paints a hostile for local target acquisition. As a side benefit, it triggers the enemy mech's danger-proximity sensors, effectively treating you as if you were an active supernova." },
  { key: 'r2-47', rank: 2, name: 'CONTACT BOOSTERS', action: 'Reaction', tags: '1/round', desc: 'Trigger: A hostile character ends movement adjacent to you. Effect: You move 1 space in any direction. This movement ignores engagement and does not provoke reactions.', flavor: 'Ancillary boosters that are programmed to activate when they detect the immediate proximity of hostile units.' },
  { key: 'r2-48', rank: 2, name: 'IFF SMART MUNITIONS', action: 'Passive', tags: '', desc: 'You and your allies gain Immunity to damage from your own Blast and Cone attacks.', flavor: 'Become the most popular guy in the hangar.' },
  { key: 'r2-49', rank: 2, name: 'REFLECTIVE COATING', action: 'Free Action', tags: '1/scene', desc: '1/scene, you may Hide as a free action.', flavor: 'A special coat of paint made from reflective alloys. A cheaper, if less reliable, stealth doctrine.' },
  { key: 'r2-50', rank: 2, name: '"OH CRAP" BUTTON', action: 'Free Action', tags: '1/scene', desc: '1/scene, If you miss with a Superheavy weapon, you may immediately Boost your speed in any direction.', flavor: "A big red button that, when pressed, activates your mech's boosters. Good way to get out of a bad play." },
];

export function rareReserveByKey(key) {
  return RARE_RESERVES.find((r) => r.key === key) || null;
}

// Резерв, узятий зі складу, лежить у тому самому state.reserves, що й куплений за PR,
// тож списки «на руках» і запис про згорання мають знаходити і звичайні, і рідкісні.
// reserveByKey навмисно лишається тільки для звичайних: рідкісний не можна ні купити,
// ні зробити через Get Creative.
export function anyReserveByKey(key) {
  return RESERVES.find((r) => r.key === key) || rareReserveByKey(key);
}
